
# Site settings

# NB! Set your site's url, otherwise stuff will break :)

url: "https://nav272.github.io"

# If you're hosting your site at a Project repository on GitHub pages
# (https://yourusername.github.io/repository-name)
# and NOT your user repository (https://yourusername.github.io)
# then add in the baseurl here, like this: "/repository-name"
#
# NB! Without this *nothing* will work, because it's used in every path :)

baseurl: /Newb

# Google tracking id

google-tracking-id: ""

# Forces https everywhere in your website, except when you serve it locally
# If you are not hosted on Github Pages, and your host doesn't support https
# then you should disable it

force-https: True

#############
# HTML Head #
#############

lang: "en"
author: "Namrata Vichare"
title: "Wīzard Dīarīes"
description: "a noob."
keywords: "namrata, vichare, cybersecurity, books"
favicon: "/img/favicon.ico"

################
# Header layout #
################

#black-favicon: "/img/black-lab-glass.ico"
#logo: "/img/author.png" # leave blank if you don't want a logo

background-img: "../img/intro-bg.jpg"

##############################
# Dynamic Text on the Header #
##############################

dynamic-typing: True
shuffle: True # Shuffle the lines.
loop: True
loop-count: False # Set False for infinite loop, or set any number for finite loop.
type-speed: 10
start-delay: 200
delete-delay: 5000
lines: # You can add HTML Tags in the Text
  - text: "Learning from all the Harrys, Hermiones and Rons in the world"
  - text: "Striving to be a better Hermione"
  

me-img: "/img/hermionelaughing.jpg"

# To use facebook profile pic comment the previous line and uncomment the following
# line, and replace 'user_id' with your facebook user id.
# Facebook user id can be found by clicking on your profile pic and the large number
# in the end of the url just before '&type' is your user id.
# Note: fbid is not the same as user id and user id only contains numbers

# me-img: "https://graph.facebook.com/user_id/picture?type=large&width=500&height=500"

# To use github profile pic uncomment the following line and replace 'user_name'
# with your github user name.

# me-img: "https://github.com/user_name.png?size=500"

# To use gravatar profile pic uncomment the following line and replace 'email_hash'
# with your gravatar profile email hash.
# You can create the email hash by using an online tool like 'http://www.md5hashgenerator.com/'
# just enter your email and it will generate the hash.

# me-img: "https://www.gravatar.com/avatar/email_hash?s=500"

##############################
# Color the browser elements #
##############################
color-browser: "#1B1717"
apple-status-bar-style: "#1B1717"

################
# Web app mode #
################

web-app-mode: False

# Icons for Web App mode

icon-36p: "/img/web-app/icon-36p.png"
icon-48p: "/img/web-app/icon-48p.png"
icon-72p: "/img/web-app/icon-72p.png"
icon-96p: "/img/web-app/icon-96p.png"
icon-144p: "/img/web-app/icon-144p.png"
icon-192p: "/img/web-app/icon-192p.png"

########
# Blog #
########

enable-gesture-navigation: True

post-preview-words: 96

paginate: 5

email-share: False
fb-share: False
twitter-share: False
linkedin-share: False 
reddit-share: False
google-plus-share: False
tumblr-share: False
pinterest-share: False
pocket-share: False
vkontakte-share: False

#disqus-shortname: "personal-jekyll-theme"

syntax-highlight: True

############
# Timeline #
############
   #Current Scientist mode: MinistryofMagicaurordivison.jpg
    #Dataprise: image pending 
    #NYU graduation: hogwartscastle.jpg
    #Graduate Assistant: Learning.jpg or some other appropriate image
    #GTU graduation: graduateHermione.jpg
    #Hitachi: Image pending 
    #School Graduation hogwarts 
events:
  - image: "/img/timeline/light.jpg"
    date: "Present"
    description: "A skilled Auror looking to solve problems and learn new and compelling skills"
  - image: "/img/timeline/fire.jpg"
    date: "Apr 2021"
    description: "Successfully managed to put out all fires and provided excellent auror services"
  - image: "/img/timeline/ministryofmagic.jpg"
    date: "Oct 2018"
    description: "A newb auror started working as a **Network Architecture and Security Engineer** at **Dataprise NY**"
  - image: "/img/timeline/hogwartscastle.jpg"
    date: "May 2018"
    description: "An auror: Graduated from **NYU (MS in Computer Engineering)**"
  - image: "/img/timeline/harryDumbledore.jpg"
    date: "May 2018"
    description: "Farewell to the Mathematics department"
  - image: "/img/timeline/class.jpg"
    date: "May 2017"
    description: "A journey of logic and fun: Started at NYU as a Graduate Assistant in Mathematics to Prof. Erwin Lutwak"
  - image: "/img/timeline/unravellingmysteries.jpg"
    date: "Aug 2016"
    description: "To become a skilled auror, started at **New York University**"
  - image: "/img/timeline/graduateHermione.jpg"
    date: "Jul 2015"
    description: "Distinguished NEWT: Bachelor of Engineering from GTU in Electronics and Communications Engineering"
  - image: "/img/timeline/Patronus.jpg"
    date: "Apr 2015"
    description: "Became skilled at spells which can automate the things you want to get done."
  - image: "/img/timeline/workandlearning.jpg"
    date: "Aug 2014"
    description: "My first real-life magical encounter: Started working at **Hitachi**"
  - image: "/img/timeline/ThePlacetoLearn.jpg"
    date: "Aug 2011"
    description: "Hogwarts <3 Started at **Gujarat Technological University**"
  - image: "/img/timeline/community.jpg"
    date: "Jun 2011"
    description: "Discovered the arts of wizardry from **St. Xavier's School, Gandhinagar**"
# First image of the Timeline

timeline-img: "/img/timeline/imagination.jpg"

###########
# Contact #
###########

email: "HermioneCodes@protonmail.com"


# Set a url pointing to your publish PGP Public Key here, and it will appear in the Contact section
pgp: False

################
# Author Blurb #
################

# The author blurb goes underneath blog posts.
# This works best when your author blurb image has a transparent background, or matches your site background color.

# if the author_blurb is not set, then this feature is skipped
author_blurb: "This Potterhead thinks code can create magic you envisioned and it has been successful so far. I believe reading can help me save some portion of the neighborhood, but, my friend, you can help me save the world. So, do contact me if you feel like this is something I can help you with, trust me I won't say no, unless I absolutely can't."
author_blurb_image: "/img/author.png"

##################
# Social Buttons #
##################

social:
  - title: "linkedin"
    url: "https://www.linkedin.com/in/namrata-v-6a5577130/"
  - title: "github"
    url: "https://github.com/nav272"
  ############
# 404 page #
############

err-404-img: "/img/hermioneexperiments.png"

##################
# GPG on Keybase #
##################

keybase-username: nav272
keybase-in-social: True
keybase-in-footer: True

################################################################################

# NB! Tread carefully if you want to change the variables below this point!

# Sections shown in the index page

pages_list:
  About: 'about'
  Blog: 'latest-post'
  Timeline: 'timeline'
  Contact: 'contact'

# Exclusion list from the generated _site

exclude: ["LICENSE", "README.md", "CONTRIBUTING", "CONTRIBUTORS", "scripts"]

# Pagination path

paginate_path: "blog/page:num/"

# Enable minification SASS

sass:
  style: compressed

plugins:
  - jekyll-paginate
  - jemoji
